# Enter your per-environment constants below

development: &default
  base_url:  "http://localhost:3000/"
  constant2:  "value2"

production:
  <<: *default
  constant1:  "overriden value1e"
  
test:
  <<: *default